# ansible/roles/llm-mlx/handlers/main.yml
---
- name: restart mlx-server
  shell: |
    launchctl bootout system/com.hydra.mlx-server 2>/dev/null || true
    launchctl bootstrap system /Library/LaunchDaemons/com.hydra.mlx-server.plist
  become: true
  ignore_errors: true

- name: restart mlx-logexporter
  shell: |
    launchctl bootout system/com.hydra.mlx-logexporter 2>/dev/null || true
    launchctl bootstrap system /Library/LaunchDaemons/com.hydra.mlx-logexporter.plist
  become: true
  ignore_errors: true
