# monitoring/grafana/provisioning/datasources/datasources.yml
apiVersion: 1

datasources:
  - name: VictoriaMetrics
    type: prometheus
    uid: victoria-metrics
    url: http://victoria-metrics:8428
    access: proxy
    isDefault: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"

  - name: Loki
    type: loki
    uid: loki
    url: http://loki:3100
    access: proxy
    jsonData:
      maxLines: 5000

  - name: Alertmanager
    type: alertmanager
    uid: alertmanager
    url: http://alertmanager:9093
    access: proxy
    jsonData:
      handleGrafanaManagedAlerts: false
      implementation: prometheus

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    uid: tempo
